version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules   # do not try to map the folder up against the app/node_modules inside the container
      - .:/app  # : is used to map the folder outside and inside the container
    tty: true